services:
  libraryApp:
    image: thaliapawn/library-node-app:1.4.0
    container_name: libraryApp
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  viewsService:
    image: thaliapawn/book-view-service:1.0.0
    container_name: viewsService
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  mongo:
    image: mongo:noble
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: "true"
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass
    depends_on:
      - mongo